apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /flask
            pathType: Prefix
            backend:
              service:
                name:  {{ .Chart.Name }}
                port:
                  number: {{ .Values.service.port }}